name: atom-fusion
version: 1.8.0
summary: Atom Text Editor
description: Atom Text editor, from GitHub
confinement: devmode

apps:
  atom:
    command: bin/wrapper
    plugs: [home]

parts:
  atom:
    source: https://github.com/atom/atom/archive/v1.8.0.tar.gz
    plugin: nodejs
    gruntfile: build/Gruntfile.coffee
    stage-packages: [git, gconf2, gconf-service, libgtk2.0-0, libudev1, libgcrypt20, libnotify4, libxtst6, libnss3, python, gvfs-bin, xdg-utils, libcap2]
    build-packages: [build-essential, git, libgnome-keyring-dev, fakeroot]
  atom-copy:
    plugin: copy
    source: .
    files:
      wrapper: bin/wrapper
